[package]
name = "advent_of_bevy_2025"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = { version = "0.17.3", features = ["experimental_bevy_feathers"] }
rand = "*"
bevy_pkv = "*"
serde = "*"
strum_macros = "*"
chrono = "*"

[profile.dev.package."*"]
opt-level = 3